name: win

on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: relwithdebinfo

jobs:
  win:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
          os: [windows-latest]
          visual_studio: ["Visual Studio 16 2019", "Visual Studio 17 2022"]
          vcpkg_triplet: ["x64-windows"]

    steps:
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: glad opengl glfw3
          triplet: ${{ matrix.vcpkg_triplet }}
          cache-key: ${{ matrix.os }}
          token: ${{ github.token }}
          github-binarycache: true

      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{runner.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        shell: bash
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Status
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Set Status'
          description: 'Passed'
          state: 'success'

